---
- name: Update httpd package on servers in development environment
  hosts: development_servers
  become: true

  tasks:
    - name: Gather package facts
      package_facts:

    - name: Update httpd package
      yum:
        name: httpd
        state: latest
      when: "'httpd' in ansible_facts.packages"