---
Certainly! Below is a sample Ansible playbook that will update the `httpd` package to the latest version on systems where `httpd` is installed. It will skip updating or installing `httpd` on systems where it is not present. This playbook will be executed on all hosts specified in the inventory file.


---
- name: Update httpd to latest version on systems where httpd is installed
  hosts: all
  become: yes

  tasks:
    - name: Check if httpd is installed
      stat:
        path: /usr/sbin/httpd
      register: httpd_installed

    - name: Update httpd package
      yum:
        name: httpd
        state: latest
      when: httpd_installed.stat.exists


You can save this playbook in a file, for example `update_httpd.yml`, and run it using the `ansible-playbook` command:

shell
ansible-playbook -i inventory_file update_httpd.yml


Please ensure you have appropriate permissions to run commands with `sudo` or act as a privileged user using Ansible's become feature.