---
- hosts: 192.168.1.133
  tasks:
    - name: Restart httpd service
      service:
        name: httpd
        state: restarted


This playbook will restart the httpd service on the server with the IP address 192.168.1.133.