---
---
- name: Resolve httpd service down issue on server 192.168.1.100
  hosts: 192.168.1.100
  tasks:

    - name: Ensure httpd service is running
      service:
        name: httpd
        state: started