---
- name: Update httpd package on the affected server
  hosts: 192.168.1.100
  become: yes

  tasks:
    - name: Update the httpd package
      yum:
        name: httpd
        state: latest
      notify: Restart httpd service

  handlers:
    - name: Restart httpd service
      systemd:
        name: httpd
        state: restarted