---
- hosts: development_servers
  become: yes
  tasks:
    - name: Gather package facts
      package_facts:

    - name: Update httpd package
      yum:
        name: httpd
        state: latest
      when: "'httpd' in ansible_facts.packages"